// Fallback copy of the stdlib source. GENERATED, do not edit.
//
// Regenerate with:  python compiler/embed_std.py
//
// Included by std_src.c only when the compiler has no #embed.

static const char src_math[] =
    "// The `math` module.\n"
    "//\n"
    "// Compiled into the Solis binary; `import math;` needs no file on disk.\n"
    "// The `extern` declarations are backed by native code, and everything else is\n"
    "// ordinary Solis.\n"
    "//\n"
    "// Note there is no overloading and no generics, so int and float versions are\n"
    "// separate functions. `maxf` is the float twin of `max`. That is the honest\n"
    "// cost of the trim, and it is better than pretending.\n"
    "\n"
    "// Solis never converts between int and float implicitly, so these are the only\n"
    "// way across. You will reach for `toFloat` constantly when averaging.\n"
    "\n"
    "extern func toFloat(n: int): float;\n"
    "// Truncates toward zero.\n"
    "extern func toInt(x: float): int;\n"
    "\n"
    "extern func floor(x: float): int;\n"
    "extern func ceil(x: float): int;\n"
    "extern func round(x: float): int;\n"
    "\n"
    "extern func sqrt(x: float): float;\n"
    "extern func pow(base: float, exp: float): float;\n"
    "extern func exp(x: float): float;\n"
    "extern func ln(x: float): float;\n"
    "extern func log10(x: float): float;\n"
    "\n"
    "extern func sin(x: float): float;\n"
    "extern func cos(x: float): float;\n"
    "extern func tan(x: float): float;\n"
    "extern func atan2(y: float, x: float): float;\n"
    "\n"
    "extern func abs(x: float): float;\n"
    "extern func absInt(n: int): int;\n"
    "\n"
    "let PI = 3.141592653589793;\n"
    "let E = 2.718281828459045;\n"
    "let TAU = 6.283185307179586;\n"
    "\n"
    "func min(a: int, b: int): int {\n"
    "    if a < b {\n"
    "        return a;\n"
    "    }\n"
    "    return b;\n"
    "}\n"
    "\n"
    "func max(a: int, b: int): int {\n"
    "    if a > b {\n"
    "        return a;\n"
    "    }\n"
    "    return b;\n"
    "}\n"
    "\n"
    "func minf(a: float, b: float): float {\n"
    "    if a < b {\n"
    "        return a;\n"
    "    }\n"
    "    return b;\n"
    "}\n"
    "\n"
    "func maxf(a: float, b: float): float {\n"
    "    if a > b {\n"
    "        return a;\n"
    "    }\n"
    "    return b;\n"
    "}\n"
    "\n"
    "func clamp(v: int, lo: int, hi: int): int {\n"
    "    return min(max(v, lo), hi);\n"
    "}\n"
    "\n"
    "func clampf(v: float, lo: float, hi: float): float {\n"
    "    return minf(maxf(v, lo), hi);\n"
    "}\n"
    "\n"
    "func sign(n: int): int {\n"
    "    if n > 0 {\n"
    "        return 1;\n"
    "    }\n"
    "    if n < 0 {\n"
    "        return 0 - 1;\n"
    "    }\n"
    "    return 0;\n"
    "}\n"
    "\n"
    "// Linear interpolation. `t` is not clamped.\n"
    "func lerp(a: float, b: float, t: float): float {\n"
    "    return a + (b - a) * t;\n"
    "}\n"
    "\n"
    "func degrees(radians: float): float {\n"
    "    return radians * 180.0 / PI;\n"
    "}\n"
    "\n"
    "func radians(degrees: float): float {\n"
    "    return degrees * PI / 180.0;\n"
    "}\n"
    "\n";

static const char src_strings[] =
    "// The `strings` module.\n"
    "//\n"
    "// Named `strings` rather than `str` so it cannot be confused with the `str`\n"
    "// type. Indices are in characters, not bytes, so non-ASCII text behaves the\n"
    "// way a reader expects.\n"
    "//\n"
    "// There are no optionals, so searches return -1 for \"not found\" rather than\n"
    "// null, and `toInt` pairs with `isInt` instead of failing.\n"
    "\n"
    "extern func len(s: str): int;\n"
    "\n"
    "// Characters from `start` up to but not including `end`. Out-of-range\n"
    "// positions are clamped rather than being an error.\n"
    "extern func sub(s: str, start: int, end: int): str;\n"
    "\n"
    "// The character at `i`, as a one-character string. Empty if out of range.\n"
    "extern func at(s: str, i: int): str;\n"
    "\n"
    "// Character index of the first occurrence, or -1.\n"
    "extern func indexOf(s: str, needle: str): int;\n"
    "extern func contains(s: str, needle: str): bool;\n"
    "extern func startsWith(s: str, prefix: str): bool;\n"
    "extern func endsWith(s: str, suffix: str): bool;\n"
    "\n"
    "extern func upper(s: str): str;\n"
    "extern func lower(s: str): str;\n"
    "extern func trim(s: str): str;\n"
    "extern func repeat(s: str, n: int): str;\n"
    "extern func replace(s: str, from: str, to: str): str;\n"
    "extern func reverse(s: str): str;\n"
    "\n"
    "extern func split(s: str, sep: str): [str];\n"
    "extern func join(parts: [str], sep: str): str;\n"
    "extern func chars(s: str): [str];\n"
    "\n"
    "extern func fromInt(n: int): str;\n"
    "extern func fromFloat(x: float): str;\n"
    "extern func fromBool(b: bool): str;\n"
    "\n"
    "// Parses a decimal integer, with an optional leading `-`. Returns 0 when the\n"
    "// string is not one, so check with `isInt` first if that matters.\n"
    "extern func toInt(s: str): int;\n"
    "extern func isInt(s: str): bool;\n"
    "\n"
    "func isEmpty(s: str): bool {\n"
    "    return len(s) == 0;\n"
    "}\n"
    "\n"
    "func padLeft(s: str, width: int, fill: str): str {\n"
    "    var out = s;\n"
    "    while len(out) < width {\n"
    "        out = fill + out;\n"
    "    }\n"
    "    return out;\n"
    "}\n"
    "\n"
    "func padRight(s: str, width: int, fill: str): str {\n"
    "    var out = s;\n"
    "    while len(out) < width {\n"
    "        out = out + fill;\n"
    "    }\n"
    "    return out;\n"
    "}\n"
    "\n"
    "func count(s: str, needle: str): int {\n"
    "    if isEmpty(needle) {\n"
    "        return 0;\n"
    "    }\n"
    "    var n = 0;\n"
    "    var rest = s;\n"
    "    var atIndex = indexOf(rest, needle);\n"
    "    while atIndex >= 0 {\n"
    "        n += 1;\n"
    "        rest = sub(rest, atIndex + len(needle), len(rest));\n"
    "        atIndex = indexOf(rest, needle);\n"
    "    }\n"
    "    return n;\n"
    "}\n"
    "\n"
    "// Everything before the first `sep`, or the whole string if absent.\n"
    "func before(s: str, sep: str): str {\n"
    "    let i = indexOf(s, sep);\n"
    "    if i < 0 {\n"
    "        return s;\n"
    "    }\n"
    "    return sub(s, 0, i);\n"
    "}\n"
    "\n"
    "// Everything after the first `sep`, or the empty string if absent.\n"
    "func after(s: str, sep: str): str {\n"
    "    let i = indexOf(s, sep);\n"
    "    if i < 0 {\n"
    "        return \"\";\n"
    "    }\n"
    "    return sub(s, i + len(sep), len(s));\n"
    "}\n"
    "\n";

static const char src_io[] =
    "// The `io` module: standard input, output and error.\n"
    "//\n"
    "// `print` covers most output; this is for when the newline, the stream or\n"
    "// the input matters. Only the standard interpreter opens it.\n"
    "\n"
    "// Writes with no trailing newline.\n"
    "extern func write(s: str);\n"
    "extern func writeErr(s: str);\n"
    "\n"
    "// Standard output is line buffered when it is a terminal and block buffered\n"
    "// otherwise, so this matters when output is being piped somewhere watching.\n"
    "extern func flush();\n"
    "\n"
    "// One line from standard input, without its newline. Empty at end of input,\n"
    "// which is also what an empty line gives; check `eof` to tell them apart.\n"
    "extern func readLine(): str;\n"
    "\n"
    "// Everything left on standard input.\n"
    "extern func readAll(): str;\n"
    "\n"
    "extern func eof(): bool;\n"
    "\n"
    "func writeLine(s: str) {\n"
    "    write(s);\n"
    "    write(\"\\n\");\n"
    "}\n"
    "\n"
    "func errLine(s: str) {\n"
    "    writeErr(s);\n"
    "    writeErr(\"\\n\");\n"
    "}\n"
    "\n"
    "// Every remaining line of standard input. The last line counts whether or\n"
    "// not the input ended with a newline.\n"
    "func lines(): [str] {\n"
    "    var out: [str] = [];\n"
    "    while !eof() {\n"
    "        let line = readLine();\n"
    "        if eof() && len(line) == 0 {\n"
    "            return out;\n"
    "        }\n"
    "        push(out, line);\n"
    "    }\n"
    "    return out;\n"
    "}\n"
    "\n"
    "// Prints `prompt` and reads one line, for the usual interactive case.\n"
    "func ask(prompt: str): str {\n"
    "    write(prompt);\n"
    "    flush();\n"
    "    return readLine();\n"
    "}\n"
    "\n";

static const char src_fs[] =
    "// The `fs` module: files and directories.\n"
    "//\n"
    "// No optionals: a failed read gives \"\", a failed query gives -1 or false.\n"
    "// Pair `read` with `exists` when empty-vs-missing matters. Only the\n"
    "// standard interpreter opens this.\n"
    "\n"
    "import strings;\n"
    "\n"
    "// The whole file as text. Empty if it cannot be read.\n"
    "extern func read(path: str): str;\n"
    "\n"
    "// Replaces the file. False if it could not be written.\n"
    "extern func write(path: str, text: str): bool;\n"
    "extern func append(path: str, text: str): bool;\n"
    "\n"
    "extern func exists(path: str): bool;\n"
    "extern func isDir(path: str): bool;\n"
    "\n"
    "// Size in bytes, or -1 if there is nothing there.\n"
    "extern func size(path: str): int;\n"
    "\n"
    "extern func remove(path: str): bool;\n"
    "extern func rename(from: str, to: str): bool;\n"
    "\n"
    "// Creates one directory. The parent has to exist already.\n"
    "extern func mkdir(path: str): bool;\n"
    "\n"
    "// The names in a directory, without `.` and `..` and without the directory\n"
    "// prefix. Empty if it is not a readable directory.\n"
    "extern func list(path: str): [str];\n"
    "\n"
    "func isFile(path: str): bool {\n"
    "    return exists(path) && !isDir(path);\n"
    "}\n"
    "\n"
    "// The file split into lines. A trailing newline does not produce a final\n"
    "// empty line, and \\r\\n is handled.\n"
    "func lines(path: str): [str] {\n"
    "    var text = strings.replace(read(path), \"\\r\\n\", \"\\n\");\n"
    "    if strings.endsWith(text, \"\\n\") {\n"
    "        text = strings.sub(text, 0, strings.len(text) - 1);\n"
    "    }\n"
    "    var out: [str] = [];\n"
    "    if strings.isEmpty(text) {\n"
    "        return out;\n"
    "    }\n"
    "    return strings.split(text, \"\\n\");\n"
    "}\n"
    "\n"
    "// Full paths of the entries in `dir`, so the result can be fed straight back\n"
    "// into `read` or `list`.\n"
    "func paths(dir: str): [str] {\n"
    "    var out: [str] = [];\n"
    "    for name in list(dir) {\n"
    "        push(out, dir + \"/\" + name);\n"
    "    }\n"
    "    return out;\n"
    "}\n"
    "\n"
    "// Writes `text` only if the file is absent. False if it was already there.\n"
    "func writeNew(path: str, text: str): bool {\n"
    "    if exists(path) {\n"
    "        return false;\n"
    "    }\n"
    "    return write(path, text);\n"
    "}\n"
    "\n";

static const char src_os[] =
    "// The `os` module: the process and its surroundings.\n"
    "//\n"
    "// The most ambient of the batteries: `env` reads the environment, `run`\n"
    "// starts other programs. Only the standard interpreter opens this.\n"
    "\n"
    "// Everything the interpreter was given after its own options, starting with\n"
    "// the script path itself, so `args()[0]` is the script and the rest are its\n"
    "// arguments, as in most scripting languages.\n"
    "extern func args(): [str];\n"
    "\n"
    "// The variable's value, or the empty string. `hasEnv` tells an unset\n"
    "// variable from one set to nothing.\n"
    "extern func env(name: str): str;\n"
    "extern func hasEnv(name: str): bool;\n"
    "\n"
    "// Stops immediately with this status. Nothing after it runs, and no\n"
    "// destructor does either.\n"
    "extern func exit(code: int);\n"
    "\n"
    "// One of \"windows\", \"macos\", \"linux\" or \"unix\".\n"
    "extern func platform(): str;\n"
    "\n"
    "extern func cwd(): str;\n"
    "\n"
    "// Runs a command through the system shell and returns its exit status, or\n"
    "// -1 if it could not be started. The command's output goes wherever this\n"
    "// process's output goes.\n"
    "extern func run(command: str): int;\n"
    "\n"
    "// The script's own arguments, without the script path. Index 0 is the first\n"
    "// real argument, which is what a script usually wants.\n"
    "func argv(): [str] {\n"
    "    var out: [str] = [];\n"
    "    let all = args();\n"
    "    var i = 1;\n"
    "    while i < len(all) {\n"
    "        push(out, all[i]);\n"
    "        i += 1;\n"
    "    }\n"
    "    return out;\n"
    "}\n"
    "\n"
    "// The i'th script argument, or `fallback` if it was not given.\n"
    "func arg(i: int, fallback: str): str {\n"
    "    let all = args();\n"
    "    if i + 1 >= len(all) {\n"
    "        return fallback;\n"
    "    }\n"
    "    return all[i + 1];\n"
    "}\n"
    "\n"
    "func isWindows(): bool {\n"
    "    return platform() == \"windows\";\n"
    "}\n"
    "\n"
    "// The value of an environment variable, or `fallback` when it is unset.\n"
    "func envOr(name: str, fallback: str): str {\n"
    "    if !hasEnv(name) {\n"
    "        return fallback;\n"
    "    }\n"
    "    return env(name);\n"
    "}\n"
    "\n";

static const char src_time[] =
    "// The `time` module: the clock. Ambient authority, so only the standard\n"
    "// interpreter opens it; a sandboxed host registers its own clock if needed.\n"
    "\n"
    "import strings;\n"
    "\n"
    "// Milliseconds since the Unix epoch, UTC.\n"
    "extern func nowMs(): int;\n"
    "\n"
    "// Milliseconds since the interpreter started. Use this for measuring\n"
    "// durations; it does not jump when the system clock is corrected.\n"
    "extern func monoMs(): int;\n"
    "\n"
    "extern func sleepMs(ms: int);\n"
    "\n"
    "// The current time as ISO 8601 in UTC, \"2026-10-04T18:33:07Z\".\n"
    "extern func iso(): str;\n"
    "\n"
    "func nowSec(): int {\n"
    "    return nowMs() / 1000;\n"
    "}\n"
    "\n"
    "// Today as \"2026-10-04\".\n"
    "func today(): str {\n"
    "    return strings.sub(iso(), 0, 10);\n"
    "}\n"
    "\n";

static const char src_rand[] =
    "// The `rand` module: pseudo-random numbers. xorshift64*, seeded from the\n"
    "// clock, reproducible once `seed` is called. Not cryptographic. Only the\n"
    "// standard interpreter opens this.\n"
    "\n"
    "// Fixes the sequence. Zero is replaced, because it is a fixed point of the\n"
    "// generator rather than a seed.\n"
    "extern func seed(n: int);\n"
    "\n"
    "// A number in 0 ..< n, uniformly. Zero when `n` is not positive.\n"
    "extern func below(n: int): int;\n"
    "\n"
    "// A float in 0.0 ..< 1.0.\n"
    "extern func real(): float;\n"
    "\n"
    "// A number in lo ..< hi, or `lo` if that range is empty.\n"
    "func between(lo: int, hi: int): int {\n"
    "    if hi <= lo {\n"
    "        return lo;\n"
    "    }\n"
    "    return lo + below(hi - lo);\n"
    "}\n"
    "\n"
    "// True with probability `p`.\n"
    "func chance(p: float): bool {\n"
    "    return real() < p;\n"
    "}\n"
    "\n"
    "// A float in lo ..< hi.\n"
    "func realBetween(lo: float, hi: float): float {\n"
    "    return lo + real() * (hi - lo);\n"
    "}\n"
    "\n"
    "// A valid index into an array of `count` items, or -1 when it is empty.\n"
    "func index(count: int): int {\n"
    "    if count <= 0 {\n"
    "        return 0 - 1;\n"
    "    }\n"
    "    return below(count);\n"
    "}\n"
    "\n";
