#!/usr/bin/env python3
"""Concatenate the runtime into one .c file, SQLite style.

    python tools/amalgamate.py [-o out.c]

System includes are hoisted and deduped; the runtime's own includes are
dropped since the sources follow inline. The result needs only a C99 compiler
and libm, and does not depend on the toolchain that generated it.
"""

import io
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
PARTS = ["runtime/solis.h", "runtime/solis.c", "runtime/solis_std.c"]
DEFAULT_OUT = "build/runtime.c"

SYS_INCLUDE = re.compile(r'^\s*#\s*include\s*<([^>]+)>')
LOCAL_INCLUDE = re.compile(r'^\s*#\s*include\s*"([^"]+)"')


def main():
    # Output only via -o. Bare arguments are ignored: a build system that
    # appends its input list to the command line would otherwise name a
    # source file as the destination and overwrite it.
    out_rel = DEFAULT_OUT
    args = sys.argv[1:]
    for i, a in enumerate(args):
        if a == "-o" and i + 1 < len(args):
            out_rel = args[i + 1]

    out_path = out_rel if os.path.isabs(out_rel) else os.path.join(ROOT, out_rel)
    out_path = os.path.normpath(out_path)

    sources = [os.path.normpath(os.path.join(ROOT, p)) for p in PARTS]
    if out_path in sources:
        sys.stderr.write("refusing to write over a source file: %s\n" % out_rel)
        return 2

    system = []
    body = []

    for rel in PARTS:
        path = os.path.join(ROOT, rel)
        if not os.path.exists(path):
            sys.stderr.write("missing %s\n" % rel)
            return 1

        text = io.open(path, encoding="utf-8").read()
        if "Generated by tools/amalgamate.py" in text:
            sys.stderr.write("%s is already generated output, not a source\n" % rel)
            return 2

        body.append("/* ---- %s ---- */" % rel)
        for line in text.split("\n"):
            m = SYS_INCLUDE.match(line)
            if m:
                if m.group(1) not in system:
                    system.append(m.group(1))
                continue
            if LOCAL_INCLUDE.match(line):
                continue
            body.append(re.sub(r'//.*$', '', line).rstrip())
        body.append("")

    head = ["/* Solis runtime, amalgamated. Generated by tools/amalgamate.py. */", ""]
    head += ["#include <%s>" % h for h in system]
    head.append("")

    text = "\n".join(head + body)
    d = os.path.dirname(out_path)
    if d and not os.path.isdir(d):
        os.makedirs(d)
    io.open(out_path, "w", encoding="utf-8", newline="\n").write(text)

    rel_out = os.path.relpath(out_path, ROOT).replace("\\", "/")
    print("%s: %d lines, %d bytes, %d system includes"
          % (rel_out, text.count("\n") + 1, len(text), len(system)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
